server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smalltalk?serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
jwt:
  config:
    key: smalltalk
    ttl: 36000
#    ttl: 360000
